"""V1.21 added created at, updated at and is deleted column in user record

Revision ID: 0f0a14832c76
Revises: eb1e850703c8
Create Date: 2024-10-16 11:07:56.607453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0a14832c76'
down_revision: Union[str, None] = 'eb1e850703c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user record', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user record', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user record', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user record', 'is_deleted')
    op.drop_column('user record', 'updated_at')
    op.drop_column('user record', 'created_at')
    # ### end Alembic commands ###
