"""V1.6 change product id to id

Revision ID: 0f98a0537583
Revises: bc58225e3527
Create Date: 2024-08-27 16:11:44.999111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f98a0537583'
down_revision: Union[str, None] = 'bc58225e3527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_products', sa.Column('id', sa.String(), nullable=False))
    op.drop_column('invoice_products', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_products', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('invoice_products', 'id')
    # ### end Alembic commands ###
