"""V1.14 Added Used product table

Revision ID: 1264ab9f62a4
Revises: 0901906a0ed4
Create Date: 2024-09-05 14:53:53.929399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1264ab9f62a4'
down_revision: Union[str, None] = '0901906a0ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('EPC_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'product_stock', 'master products', ['EPC_code'], ['EPC_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_stock', type_='foreignkey')
    op.drop_table('used products')
    # ### end Alembic commands ###
