"""V1.16 Added Transfer Product DB

Revision ID: 26e00124e0e0
Revises: 28834cee1780
Create Date: 2024-09-09 12:27:57.832806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26e00124e0e0'
down_revision: Union[str, None] = '28834cee1780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_transfer',
    sa.Column('transfer_id', sa.String(), nullable=False),
    sa.Column('EPC_code', sa.String(), nullable=True),
    sa.Column('from_city', sa.String(), nullable=True),
    sa.Column('to_city', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('transfer_at', sa.DateTime(), nullable=True),
    sa.Column('transfer_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['EPC_code'], ['master products.EPC_code'], ),
    sa.ForeignKeyConstraint(['from_city'], ['cities.city_id'], ),
    sa.ForeignKeyConstraint(['to_city'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.drop_table('product_trasfer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_trasfer',
    sa.Column('transfer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('from_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('to_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('transfer_id', name='product_trasfer_pkey')
    )
    op.drop_table('product_transfer')
    # ### end Alembic commands ###
