"""V1.12 change the relation ship in master products

Revision ID: 38e5fb0016e9
Revises: 7f140141c3ad
Create Date: 2024-08-31 13:23:05.648420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e5fb0016e9'
down_revision: Union[str, None] = '7f140141c3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
