"""V1.7 Added EPC code in Audit update table

Revision ID: 3e0aaf36428f
Revises: 0f98a0537583
Create Date: 2024-08-27 16:38:17.438994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0aaf36428f'
down_revision: Union[str, None] = '0f98a0537583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product update audit', sa.Column('EPC_code', sa.String(), nullable=True))
    op.drop_column('product update audit', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product update audit', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product update audit', 'EPC_code')
    # ### end Alembic commands ###
