"""V1.9 remove the unique from all category

Revision ID: 4f9d98f77736
Revises: 8a0f3bd40b34
Create Date: 2024-08-29 16:01:48.871499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9d98f77736'
down_revision: Union[str, None] = '8a0f3bd40b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('GST_gst_percentage_key', 'GST', type_='unique')
    op.drop_constraint('bikes_bike_name_key', 'bikes', type_='unique')
    op.drop_constraint('cities_city_name_key', 'cities', type_='unique')
    op.drop_constraint('colors_color_name_key', 'colors', type_='unique')
    op.drop_constraint('new_category_category_name_key', 'new_category', type_='unique')
    op.drop_constraint('size_size_name_key', 'size', type_='unique')
    op.drop_constraint('unit_unit_name_key', 'unit', type_='unique')
    op.drop_constraint('vendor_category_Vendor_name_key', 'vendor_category', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('vendor_category_Vendor_name_key', 'vendor_category', ['Vendor_name'])
    op.create_unique_constraint('unit_unit_name_key', 'unit', ['unit_name'])
    op.create_unique_constraint('size_size_name_key', 'size', ['size_name'])
    op.create_unique_constraint('new_category_category_name_key', 'new_category', ['category_name'])
    op.create_unique_constraint('colors_color_name_key', 'colors', ['color_name'])
    op.create_unique_constraint('cities_city_name_key', 'cities', ['city_name'])
    op.create_unique_constraint('bikes_bike_name_key', 'bikes', ['bike_name'])
    op.create_unique_constraint('GST_gst_percentage_key', 'GST', ['gst_percentage'])
    # ### end Alembic commands ###
