"""V1.11 Added bike association

Revision ID: 7f140141c3ad
Revises: d127ab012101
Create Date: 2024-08-31 12:42:45.715727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f140141c3ad'
down_revision: Union[str, None] = 'd127ab012101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_product_association',
    sa.Column('bike_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.bike_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['master products.EPC_code'], ),
    sa.PrimaryKeyConstraint('bike_id', 'product_id')
    )
    op.drop_column('master products', 'vendor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master products', sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('bike_product_association')
    # ### end Alembic commands ###
