"""V1.8 Implemented a couter table

Revision ID: 8a0f3bd40b34
Revises: 3e0aaf36428f
Create Date: 2024-08-28 12:33:29.066367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0f3bd40b34'
down_revision: Union[str, None] = '3e0aaf36428f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('code_id', sa.String(), nullable=False),
    sa.Column('code_name', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counter')
    # ### end Alembic commands ###
