"""V1.3 Added ID on each category

Revision ID: c0e5506b6729
Revises: 3ca0fadff24b
Create Date: 2024-08-21 18:08:10.585968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e5506b6729'
down_revision: Union[str, None] = '3ca0fadff24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
